<?xml version= '1.0'?>
<!DOCTYPE ADDRESSBOOK [
<!ELEMENT ADDRESSBOOK (PERSON)*>
<!ELEMENT PERSON (LASTNAME, FIRSTNAME, COMPANY, EMAIL)>
<!ELEMENT LASTNAME (#PCDATA)>
<!ELEMENT FIRSTNAME (#PCDATA)>
<!ELEMENT COMPANY (#PCDATA)>
<!ELEMENT EMAIL (#PCDATA)>
]>
<ADDRESSBOOK>

  <PERSON>
    <LASTNAME>Idris</LASTNAME>
    <FIRSTNAME>Nazmul</FIRSTNAME>
    <COMPANY>The Bean Factory, LLC.</COMPANY>
    <EMAIL>xml@beanfactory.com</EMAIL>
  </PERSON>

  <PERSON>
    <LASTNAME>Miyamato</LASTNAME>
    <FIRSTNAME>Musashi</FIRSTNAME>
    <COMPANY>Bushido, Inc.</COMPANY>
    <EMAIL>katana@bushido.com</EMAIL>
  </PERSON>

  <PERSON>
    <LASTNAME>Einstein</LASTNAME>
    <FIRSTNAME>Albert</FIRSTNAME>
    <COMPANY>Hasta Proton, Inc.</COMPANY>
    <EMAIL>hasta@proton.com</EMAIL>
  </PERSON>

  <PERSON>
    <LASTNAME>Hampton</LASTNAME>
    <FIRSTNAME>Ed</FIRSTNAME>
    <COMPANY>AMAC, Inc.</COMPANY>
    <EMAIL>energy@hsingi.com</EMAIL>
  </PERSON>

  <PERSON>
    <LASTNAME>wer</LASTNAME>
    <FIRSTNAME>werwer</FIRSTNAME>
    <COMPANY>wer</COMPANY>
    <EMAIL>erwer</EMAIL>
  </PERSON>

</ADDRESSBOOK>
